# Copyright (c) 2025-2026 Aegis AO Soft LLC and Alexander Orlov.
# 34 Middletown Ave, Atlantic Highlands, NJ 07716
#
# THIS SOFTWARE IS THE CONFIDENTIAL AND PROPRIETARY INFORMATION OF
# Aegis AO Soft LLC and Alexander Orlov.
#
# This code may be used, reproduced, modified, or distributed ONLY with the
# prior written permission of Aegis AO Soft LLC / Alexander Orlov.
#
# Author: Alexander Orlov
# Aegis AO Soft LLC

name: flutter_app
description: Sample Flutter app for the Aegis localizer.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
