/*
 * Copyright (c) 2025-2026 Aegis AO Soft LLC and Alexander Orlov.
 * 34 Middletown Ave, Atlantic Highlands, NJ 07716
 *
 * THIS SOFTWARE IS THE CONFIDENTIAL AND PROPRIETARY INFORMATION OF
 * Aegis AO Soft LLC and Alexander Orlov.
 *
 * This code may be used, reproduced, modified, or distributed ONLY with the
 * prior written permission of Aegis AO Soft LLC / Alexander Orlov.
 *
 * Author: Alexander Orlov
 * Aegis AO Soft LLC
 */

using Aegis.Localizer.Io;
using Aegis.Localizer.Model;
using Aegis.Localizer.Platforms;

namespace Aegis.Localizer.Scanning;

/// <summary>Walks the project tree and hands every interesting file to the adapter.</summary>
public sealed class ProjectScanner(ISourceAdapter adapter, LocalizationRequest request, string resourceDir)
{
    /// <summary>
    /// Directory names that never hold hand-written UI copy. Matched as whole path segments, so
    /// this behaves the same on Windows, macOS and Linux.
    /// </summary>
    private static readonly HashSet<string> SkipDirectories = new(StringComparer.OrdinalIgnoreCase)
    {
        "bin", "obj", "node_modules", ".git", ".hg", ".svn", ".vs", ".idea", "packages",
        "dist", "build", "out", "target", "vendor", "venv", ".venv", "__pycache__",
        "Pods", "DerivedData", ".gradle", ".dart_tool", "coverage", "TestResults",
        ".next", ".nuxt", ".svelte-kit", ".aegis-localizer"
    };

    /// <summary>Generated or vendored files whose strings are not the user's to translate.</summary>
    private static readonly string[] SkipSuffixes =
    [
        ".designer.cs", ".g.cs", ".g.i.cs", ".generated.cs", ".assemblyinfo.cs",
        ".globalusings.g.cs", ".razor.g.cs", ".freezed.dart", ".g.dart", ".pb.go",
        ".min.js", ".min.css", ".d.ts", ".bundle.js", ".chunk.js"
    ];

    /// <summary>Markers that a file came from a generator rather than a person.</summary>
    private static readonly string[] GeneratedMarkers =
    [
        "<auto-generated>", "@generated", "GENERATED CODE - DO NOT MODIFY", "Code generated by"
    ];

    public sealed record Result(List<StringCandidate> Candidates, int FilesScanned, int FilesSkipped);

    public Result Scan()
    {
        var candidates = new List<StringCandidate>();
        var scanned = 0;
        var skipped = 0;
        var nextId = 0;

        foreach (var file in EnumerateFiles())
        {
            if (request.MaxFiles > 0 && scanned >= request.MaxFiles) break;

            // Strict UTF-8: a file we cannot decode losslessly is one we must never rewrite, so it
            // is not worth extracting from either.
            var read = SourceFile.TryRead(file);
            if (read is null)
            {
                skipped++;
                continue;
            }

            var content = read.Text;

            if (IsGenerated(content))
            {
                skipped++;
                continue;
            }

            scanned++;
            var relative = Path.GetRelativePath(request.ProjectPath, file);

            List<StringCandidate> found;
            try
            {
                found = adapter.Extract(file, relative, content, request).ToList();
            }
            catch (Exception ex) when (ex is not OutOfMemoryException)
            {
                // One unparseable file must not abort a scan of thousands.
                skipped++;
                continue;
            }

            foreach (var candidate in found)
                candidates.Add(candidate with { Id = nextId++ });
        }

        return new Result(candidates, scanned, skipped);
    }

    private static bool IsGenerated(string content)
    {
        // Only the banner is inspected; that is where such markers always sit.
        var head = content.Length <= 2000 ? content : content[..2000];
        return GeneratedMarkers.Any(m => head.Contains(m, StringComparison.OrdinalIgnoreCase));
    }

    private IEnumerable<string> EnumerateFiles()
    {
        var extensions = adapter.Extensions.ToHashSet(StringComparer.OrdinalIgnoreCase);

        return DirectoryWalk.Files(request.ProjectPath)
            .Where(f => extensions.Contains(Path.GetExtension(f)))
            .Where(f => !IsExcluded(f))
            .OrderBy(f => f, StringComparer.OrdinalIgnoreCase);
    }

    private bool IsExcluded(string path)
    {
        var relative = Path.GetRelativePath(request.ProjectPath, path);

        foreach (var segment in relative.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar))
            if (SkipDirectories.Contains(segment))
                return true;

        var fileName = Path.GetFileName(path);
        if (SkipSuffixes.Any(s => fileName.EndsWith(s, StringComparison.OrdinalIgnoreCase))) return true;

        // Our own output must never be scanned back in on the next run. Guarded against an adapter
        // whose conventional resource folder IS the project root: excluding that would silently
        // skip the entire tree and report a successful scan of zero files.
        if (!IsSameFolder(resourceDir, request.ProjectPath) && IsUnder(path, resourceDir)) return true;

        var comparable = relative.Replace('\\', '/');
        return request.Exclude.Any(x =>
            comparable.Contains(x.Replace('\\', '/'), StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsUnder(string path, string folder)
    {
        var relative = Path.GetRelativePath(folder, path);
        return !relative.StartsWith("..", StringComparison.Ordinal) && !Path.IsPathRooted(relative);
    }

    private static bool IsSameFolder(string a, string b) =>
        string.Equals(
            Path.TrimEndingDirectorySeparator(Path.GetFullPath(a)),
            Path.TrimEndingDirectorySeparator(Path.GetFullPath(b)),
            StringComparison.OrdinalIgnoreCase);
}
