/*
 * Copyright (c) 2025-2026 Aegis AO Soft LLC and Alexander Orlov.
 * 34 Middletown Ave, Atlantic Highlands, NJ 07716
 *
 * THIS SOFTWARE IS THE CONFIDENTIAL AND PROPRIETARY INFORMATION OF
 * Aegis AO Soft LLC and Alexander Orlov.
 *
 * This code may be used, reproduced, modified, or distributed ONLY with the
 * prior written permission of Aegis AO Soft LLC / Alexander Orlov.
 *
 * Author: Alexander Orlov
 * Aegis AO Soft LLC
 */

using System.Text;

namespace Aegis.Localizer.Emit;

/// <summary>
/// Emits the strongly typed accessor the rewritten sources call into. A plain ResourceManager
/// wrapper on purpose: it needs no DI, works the same in ASP.NET, MAUI and WPF, and falls back to
/// the key itself if a resource is missing, so a bad rewrite degrades instead of throwing.
/// </summary>
public static class AccessorWriter
{
    public static void Write(string path, string ns, string className, string resourceBaseName, IEnumerable<string> keys)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
                      /*
                       * Copyright (c) 2025-2026 Aegis AO Soft LLC and Alexander Orlov.
                       * 34 Middletown Ave, Atlantic Highlands, NJ 07716
                       *
                       * THIS SOFTWARE IS THE CONFIDENTIAL AND PROPRIETARY INFORMATION OF
                       * Aegis AO Soft LLC and Alexander Orlov.
                       *
                       * This code may be used, reproduced, modified, or distributed ONLY with the
                       * prior written permission of Aegis AO Soft LLC / Alexander Orlov.
                       *
                       * Author: Alexander Orlov
                       * Aegis AO Soft LLC
                       */

                      // <auto-generated>
                      //     Generated by aegis-localizer. Regenerated on every run; do not edit by hand.
                      //     Translations live in the .resx files next to this file.
                      // </auto-generated>
                      """);
        sb.AppendLine();
        // Auto-generated files opt out of the project's nullable context, so state it explicitly.
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Resources;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly ResourceManager Manager =");
        sb.AppendLine($"        new(\"{resourceBaseName}\", typeof({className}).Assembly);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Overrides the culture used for lookups; falls back to CurrentUICulture.</summary>");
        sb.AppendLine("    public static CultureInfo? Culture { get; set; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Looks up a resource, returning the key itself when it is missing.</summary>");
        sb.AppendLine("    public static string Get(string key) =>");
        sb.AppendLine("        Manager.GetString(key, Culture ?? CultureInfo.CurrentUICulture) ?? key;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Looks up a format string and applies the arguments.</summary>");
        sb.AppendLine("    public static string Format(string key, params object?[] args) =>");
        sb.AppendLine("        string.Format(Culture ?? CultureInfo.CurrentUICulture, Get(key), args);");

        // The bundle can hold keys this tool never minted - a hand-written "Error.NotFound", or a
        // name that collides with a member of this class. Emitting those produces a file that does
        // not compile, so they are reachable through Get(...) but get no property.
        foreach (var key in keys.Distinct(StringComparer.Ordinal).OrderBy(k => k, StringComparer.Ordinal))
        {
            if (!IsUsableMemberName(key)) continue;

            sb.AppendLine();
            sb.AppendLine($"    public static string {key} => Get(\"{key}\");");
        }

        sb.AppendLine("}");

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(true));
    }

    /// <summary>Members of the generated class itself, which a resource key must not shadow.</summary>
    private static readonly HashSet<string> Occupied = new(StringComparer.Ordinal)
    {
        "Get", "Format", "Culture", "Manager",
        "Equals", "GetHashCode", "GetType", "ToString", "ReferenceEquals"
    };

    private static bool IsUsableMemberName(string key)
    {
        if (string.IsNullOrEmpty(key)) return false;
        if (Occupied.Contains(key)) return false;
        if (!char.IsLetter(key[0]) && key[0] != '_') return false;

        return key.All(c => char.IsLetterOrDigit(c) || c == '_');
    }
}
